version: 2
updates:
  # Rust Backend
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"

  # Vue / Bun Frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    groups:
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
          
