version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly
    groups: # group minor and patches into one PR
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
