/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('primevue/toast')['default']
  }
}

// For TSX support
declare global {
  const Button: typeof import('primevue/button')['default']
  const Checkbox: typeof import('primevue/checkbox')['default']
  const Column: typeof import('primevue/column')['default']
  const DataTable: typeof import('primevue/datatable')['default']
  const Dialog: typeof import('primevue/dialog')['default']
  const FloatLabel: typeof import('primevue/floatlabel')['default']
  const IconField: typeof import('primevue/iconfield')['default']
  const InputIcon: typeof import('primevue/inputicon')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const Menu: typeof import('primevue/menu')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Toast: typeof import('primevue/toast')['default']
}