[package]
name = "intelligence-homepage"
description = "Backend for the Homepage of the intelligence modding team"
authors = ["srendi"]
keywords = ["homepage", "blog", "backend", "surrealdb", "s3"]
license = "MIT"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[profile.release]
opt-level = 3

[dependencies]
actix-web = "4.14.0"
futures-util = "0.3.32"
env_logger = "0.11.10"
async-trait = "0.1.89"
bytes = "1.12.0"
tokio = { version = "1.52.3", features = ["fs", "rt-multi-thread"] }
surrealdb = "3.2.0-beta.2"
serde = { version = "1.0.228", features = ["derive"] }
jsonwebtoken = "10.4.0"
actix-web-httpauth = "0.8.2"
dotenv = "0.15.0"
log = "0.4.33"
