use std::cmp::PartialEq;
use std::fmt;
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use surrealdb::sql::{Datetime, Id, Thing};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct IntelliThing {
    pub(crate) id: Id,
}

impl fmt::Display for IntelliThing {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.id)
    }
}

impl PartialEq for IntelliThing {
    fn eq(&self, other: &Self) -> bool {
        other.id == self.id
    }
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct UserData {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub(crate) admin: Option<bool>,
    pub(crate) name: Option<String>,
    pub(crate) email: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) password: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) firstname: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(crate) lastname: Option<String>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct User {
    #[serde(serialize_with = "serialize_record_id")]
    pub(crate) id: IntelliThing,
    pub(crate) admin: bool,
    pub(crate) name: String,
    pub(crate) email: String,
    pub(crate) password: String,
    pub(crate) firstname: Option<String>,
    pub(crate) lastname: Option<String>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct PostData {
    #[serde(serialize_with = "serialize_option_record_id", deserialize_with = "deserialize_record_id")]
    pub(crate) author: Option<IntelliThing>,
    pub(crate) likes: Option<i32>,
    pub(crate) views: Option<i32>,
    pub(crate) title: Option<String>,
    pub(crate) posted: Option<Datetime>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct Post {
    #[serde(serialize_with = "serialize_record_id")]
    pub(crate) id: IntelliThing,
    #[serde(deserialize_with="deserialize_thing")]
    pub(crate) author: Thing,
    pub(crate) likes: i32,
    pub(crate) views: i32,
    pub(crate) title: String,
    pub(crate) posted: Datetime,
}

impl User {
    pub fn validate_password(&self, password: String) -> bool {
        // TODO implement hashing
        self.password == password
    }

    // Checks if one of the unique values is the value to compare
    pub fn compare(&self,to_compare: &String) -> bool {
        self.id == IntelliThing {id: Id::from(to_compare) } || self.name == to_compare.clone() || self.email == to_compare.clone()
    }
}

impl PostData {
    pub fn to_surreal(&self) -> surrealdb::Result<Post> {
        let author = self.author.as_ref().map(|author| {
            Thing::from(("user", author.id.clone()))
        });

        Ok(Post {
            id: IntelliThing { id: Id::rand() }, // This will be generated by SurrealDB
            author: Thing::from(("user", Id::rand())),
            likes: self.likes.unwrap_or(0),
            views: self.views.unwrap_or(0),
            title: self.title.clone().unwrap_or_default(),
            posted: self.posted.clone().unwrap_or(Datetime::default()),
        })
    }
}

fn serialize_record_id<S>(record_id: &IntelliThing, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
{
    serializer.serialize_str(&record_id.id.to_string())
}

fn serialize_thing<S>(record_id: &Thing, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    serializer.serialize_str(&record_id.id.to_string())
}

fn serialize_option_record_id<S>(record_id: &Option<IntelliThing>, serializer: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    match record_id {
        None => {
            Ok(serializer.serialize_str("")?) 
        }
        Some(something) => {
            serializer.serialize_str(&something.id.to_string())
        }
    }
}

fn deserialize_record_id<'de, D>(deserializer: D) -> Result<Option<IntelliThing>, D::Error>
where D: Deserializer<'de> {
    let buf = String::deserialize(deserializer)?;

    Ok(Some(IntelliThing { id: Id::String(buf) }))
}

fn deserialize_thing<'de, D>(deserializer: D) -> Result<Thing, D::Error>
where D: Deserializer<'de> {
    let buf = String::deserialize(deserializer)?;

    Ok(Thing::from(("", Id::from(buf))))
}